Repository UKHomeOffice/hocs-case-creator, pull requests merged in 2022-08, with the labels that each got.

#151 🧱 HOCS-5438: Support multi arch builds
  Dockerfile
Labels: minor, smoketest

#156 HOCS-4765: update schema version dependency
  build.gradle
Labels: minor

#157 Alter maxUnavailable to 0 based on prod experience
  kube/kd/deployment.yaml
Labels: patch
