Repository UKHomeOffice/hocs-case-creator, pull requests merged in 2022-09, with the labels that each got.

#158 HOCS-5305: Add deployment step for cs-prod-migration
  .drone.yml
Labels: minor

#160 HOCS-2239: Remove redundant certs container
  kube/kd/deployment.yaml
Labels: patch

#163 HOCS-4740: Missing fields from UKVI WebForm
  build.gradle
Labels: minor

#169 :memo: Update README contents
  README.md
Labels: skip-release
