Repository UKHomeOffice/hocs-case-creator, pull requests merged in 2023-02, with the labels that each got.

#202 HOCS-6241: enable queue listeners through profile
  src/main/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListener.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/ConditionalBeanTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/MigrationQueueListenerIntegrationTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/UkviQueueListenerIntegrationTest.java
Labels: major

#204 HOCS-6243: use boolean for message handle disablement
  helm/hocs-case-creator.yaml
  helm/hocs-case-migrator.yaml
  src/main/java/uk/gov/digital/ho/hocs/queue/common/BaseMessageHandler.java
  src/main/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintMessageHandler.java
  src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageHandler.java
  src/main/resources/application.yml
  src/test/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListenerTest.java
Labels: major

#208 HOCS-6257: change identity properties
  .drone.yml
  src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintService.java
  src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseService.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: major

#212 HOCS-6249: change client context use
  src/main/java/uk/gov/digital/ho/hocs/application/aspects/QueueListenerContextAspect.java
  src/main/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/queue/common/QueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintMessageHandler.java
  src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintService.java
  src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseService.java
  src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageHandler.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListenerTest.java
  src/test/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintServiceTest.java
Labels: minor

#214 HOCS-6249: reorder ignoring messages
  src/main/java/uk/gov/digital/ho/hocs/domain/service/MessageLogService.java
  src/main/java/uk/gov/digital/ho/hocs/entrypoint/MigrationQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/entrypoint/UkviQueueListener.java
Labels: patch

#220 HOCS-3567: COMP display webform enums as readable
  src/main/resources/config/enum-mappings.json
Labels: patch

#225 Update README
  README.md
Labels: skip-release

#222 Standardise queue properties
  .drone.yml
  README.md
  src/main/java/uk/gov/digital/ho/hocs/application/aws/SqsConfiguration.java
  src/main/java/uk/gov/digital/ho/hocs/application/aws/SqsMessageListenerContainerFactory.java
  src/main/java/uk/gov/digital/ho/hocs/entrypoint/MigrationQueueListener.java
  src/main/java/uk/gov/digital/ho/hocs/entrypoint/UkviQueueListener.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/test/java/uk/gov/digital/ho/hocs/entrypoint/integration/AwsSqsIntegrationTestBase.java
  src/test/java/uk/gov/digital/ho/hocs/entrypoint/integration/MigrationQueueListenerIntegrationTest.java
Labels: major
